---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
```

Q1.1

```{r}
card_base <- clean_names(CardBase)

customer_base <- clean_names(CustomerBase)

fraud_base <- clean_names(FraudBase)

transaction_base <- clean_names(TransactionBase)
```


Q1.2

```{r}
card_customer_info <- card_base %>% 
  
left_join(customer_base, by = c("cust_id" = "cust_id"))

card_customer_info
```


Q1.3

```{r}
fraud_transaction_info <- fraud_base %>% 
  right_join(transaction_base, by = c("transaction_id" = "transaction_id"))

fraud_transaction_info
```


Q1.4

```{r}
card_transaction_info <- card_base %>% 
  semi_join(transaction_base, by = c("card_number" = "credit_card_id"))
  
card_transaction_info
```


Q1.5

```{r}
hat_separated <- hat_observations %>% 
  separate(observation, 
           c("hat_colour", "hat_type"),
           sep = ",")

head(hat_separated)
```


Q1.6
```{r}
hat_coded <- hat_separated %>% 
  unite(date, 
        c("day", "month", "year"),
        sep = "/")

head(hat_coded)
```


```{r}
date_of_most_berets <-  hat_coded %>% 
  filter(hat_type == "beret") %>% 
  slice_max(observation_count, n=1) %>% 
  pull(date)
  
```


Q2.1

```{r}
card_customer_combined <-  card_base %>% 
  left_join(customer_base, by = c("cust_id" = "cust_id"))
```

```{r}
card_customer_transaction <- card_customer_combined %>% 
  right_join(transaction_base, by =c("card_number" = "credit_card_id"))

card_customer_transaction
```

```{r}
all_data_combined <-card_customer_transaction %>% 
 right_join(fraud_base, by = "transaction_id")

all_data_combined
```



Q2.2

```{r}
exam_scores_long <- exam_scores %>% 
  pivot_longer(cols = starts_with("exam_Q"),
               names_to = "exam_question",
               values_to = "score")

exam_scores_long_clean <- exam_scores_long %>% 
  separate(exam_question, 
           c("exam", "question"),
           sep = "_Q") %>% 
  select(-exam) %>% 
  mutate(question = as.numeric(question))

exam_scores_long_clean
```

