---
title: "R Notebook"
output: html_notebook
---

```{r}
library(CodeClanData)
library(tidyverse)
library(janitor)
library(dplyr)
```

```{r}
read_csv(data/books.csv)
```

```{r}
dim(books) # Quick summary of size of dataset

head(books) # Quick look at all columns

glimpse(books) #Keep title, authors, average_rating, num_pages, ratings_count

sum(is.na(books)) #No NAs
```

 
```{r}
books %>% 
select(distinct(authors)) #Look at all different authors
```

```{r}
books_trimmed <- books %>% 
  select(title, authors, average_rating, num_pages, ratings_count) 
# Trimming down dataset
```


```{r}
books_trimmed %>% 
  group_by(authors) %>% 
  summarise(median_author_rating = median(average_rating)) %>% 
  arrange(desc(median_author_rating)) # Looking at top rated authors
```

```{r}
books_trimmed <- books_trimmed %>% 
  mutate(ratings_count = na_if(ratings_count, 0)) # Turn 0 reviews into NA
```

```{r}
books_trimmed <- books_trimmed %>% 
  drop_na() # Getting rid of NAs
```

```{r}
books_trimmed %>% 
  group_by(authors) %>% 
  mutate(median_author_rating = median(average_rating)) # Adding columns
```


```{r}
books_trimmed <- books_trimmed %>% 
  group_by(authors) %>% 
  mutate(median(average_rating)) # More playing around

```

```{r}
books_trimmed <- books_trimmed %>% 
  select(authors, ratings_count, `median(average_rating)`) # Trimming further
```


```{r}
books_trimmed <-  books_trimmed %>% 
 rename("median_rating" =  "median(average_rating)" ) # Renaming columns

books_trimmed
  
```


```{r}
books_trimmed_above_9 <- books_trimmed  %>% 
  filter(median_rating >= 4.5) # Filtering for highest rated books, above 4.5/5
```


```{r}
books_trimmed_above_9 %>% 


  summarise(authors, ratings_count, median_rating
            ) %>% 
  arrange(desc(ratings_count)) # Just playing around
  
```



```{r}
books_trimmed_above_9 <- books_trimmed_above_9 %>% 
  group_by(authors) %>% 
  summarise(total_count = sum(ratings_count), 
            median_rating = median(median_rating)) #Changing dataset
```

```{r}
books_trimmed_above_9 %>% 
  arrange(desc(total_count)) # Arrange by votes lowest to highest
```

#Books had previously been trimmed to three columns: author, ratings_count, and a median of the rating
```{r}
books_trimmed_above_9 <- books_trimmed  %>% 
  filter(median_rating >= 4.5)
```

```{r}
books_trimmed_JK_and_JRR <- books_trimmed_above_9 %>% 
  filter(grepl("J.K. Rowling|J.R.R. Tolkien", authors)) # filter by author, only
# JK and JRR
```



```{r}
books %>% 
  filter(authors =="J.K. Rowling" | "J.R.R. Tolkien")
```

